### ISSUE TITLE
[Wishlist] Print reno note files between the two commits

### ISSUE THREAD

**Issue by alextricity25** [major/osa_differ#5]
In addition to printing the commits and their description between two commits, it would awesome if osa-differ also printed the reno note files that have been changed or introduced between the two commits.

It might be possible to do this using reno's ``report`` command with the ``--earliest-release`` flag. The only problem here is that the flag only takes in a packaged release, not a SHA.

I talked with @dhellmann on IRC regarding this, and he suggested that he is open to modifying reno so that this argument can take in a SHA. I'm going to take this approach first.

If we can get reno to behave the way we want, then it will be a matter of capturing the output, possibly with ``subprocess`` or ``sh`` module, then optionally displaying it as part of the osa-differ report.

**Comment by major** [comment]
Seems like a fine idea to me, but I don't have enough cycles to go implement it. :(

**Comment by alextricity25** [comment]
@major I can give this a shot. Can you assign it to me?

**Comment by major** [comment]
@alextricity25 Done!

**Comment by alextricity25** [comment]
I have a WIP branch up on my forked repo: 
https://github.com/alextricity25/osa_differ/commit/e4f284f5663f6f68729ed61727b333ef248448a8

Right now I'm taking the approach of printing out the release notes of the released tags between two SHAs.
So if ``osa_old_commit`` is on 13.4.0-33-<sha>, and ``osa_new_commit`` is on 14.0.8, it'll print all of the release notes between 13.4.0 and 14.0.8, including the rc and b releases. ``git describe`` is used to figure out what the closes tag to a commit SHA is.

The solution is very trivial. It gets a list of available tags using ``git tags``, then sorts them using the ``LooseVersion`` class in ``distutils.version``. There are few things done to get the list the way we want it(i.e. have versions with rc or b releases print before the rc or b releases). Once that list is built, the reno command is run for each tag using the ``--earliest-version`` flag. This will print out all of the release notes for that version.

Because I'm printing the release notes for all of the packaged releases between two SHAs, that means that there is the possibility that a release note may appear twice in the osa-differ output. This is because release notes made in minor releases appear again in the subsequent major release. I figure this is okay, since it's natural reno behavior.

**Comment by alextricity25** [comment]
PR is up and ready for review:
https://github.com/major/osa_differ/pull/8

**Comment by alextricity25** [comment]
Complete! Thanks major!
